name: task_2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  easy_localization: ^3.0.1
  country_pickers: ^2.0.0
  image_picker: ^0.8.6
  pin_code_fields: ^7.4.0
  hexcolor: ^2.0.7
  custom_timer: ^0.2.3
  card_swiper: ^2.0.4
  kiwi: ^4.0.2
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.16
  dio: ^4.0.6
  quick_log: ^5.2.1
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/URW DIN Arabic.ttf
    - family: Black
      fonts:
        - asset: assets/fonts/URW DIN Arabic Black.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/URW DIN Arabic Bold.ttf
    - family: Cond
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond.ttf
    - family: Cond Black
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond Black.ttf
    - family: Cond Bold
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond Bold.ttf
    - family: Cond Demi
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond Demi.ttf
    - family: Cond Light
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond Light.ttf
    - family: Cond Medium
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond Medium.ttf
    - family: Cond Thin
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond Thin.ttf
    - family: Cond XLight
      fonts:
        - asset: assets/fonts/URW DIN Arabic Cond XLight.ttf
    - family: Demi
      fonts:
        - asset: assets/fonts/URW DIN Arabic Demi.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/URW DIN Arabic Light.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/URW DIN Arabic Medium.ttf
    - family: Semi Cond
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond.ttf
    - family: Semi Cond Black
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond Black.ttf
    - family: Semi Cond Bold
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond Bold.ttf
    - family: Semi Cond Demi
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond Demi.ttf
    - family: Semi Cond Light
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond Light.ttf
    - family: Semi Cond Medium
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond Medium.ttf
    - family: Semi Cond Thin
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond Thin.ttf
    - family: Semi Cond XLight
      fonts:
        - asset: assets/fonts/URW DIN Arabic SemiCond XLight.ttf
    - family: Thin
      fonts:
        - asset: assets/fonts/URW DIN Arabic Thin.ttf
    - family: XLight
      fonts:
        - asset: assets/fonts/URW DIN Arabic XLight.ttf
  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
